ALTER TABLE [dbo].[ActividadPuestoNivel]
    ADD CONSTRAINT [PK_ActividadPuestoNivel] PRIMARY KEY CLUSTERED ([IdActividadPuestoNivel] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

