ALTER TABLE [dbo].[ActividadRate]
    ADD CONSTRAINT [PK_ActividadRate] PRIMARY KEY CLUSTERED ([IdActividadRate] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

