ALTER TABLE [dbo].[EstadoProyecto]
    ADD CONSTRAINT [PK_EstadoProyecto] PRIMARY KEY CLUSTERED ([IdEstadoProyecto] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

