ALTER TABLE [dbo].[Feriado]
    ADD CONSTRAINT [PK_Feriado_1] PRIMARY KEY CLUSTERED ([IdFeriado] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

