ALTER TABLE [dbo].[Idioma]
    ADD CONSTRAINT [PK_Idioma] PRIMARY KEY CLUSTERED ([IdIdioma] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

