ALTER TABLE [dbo].[ProyectoOT]
    ADD CONSTRAINT [PK_ProyectoOT] PRIMARY KEY CLUSTERED ([IdProyectoOt] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

