ALTER TABLE [dbo].[ProyectoActividad]
    ADD CONSTRAINT [PK_ProyectoActividad] PRIMARY KEY CLUSTERED ([IdProyectoActividad] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

