ALTER TABLE [dbo].[ProyectoVersion]
    ADD CONSTRAINT [PK_ProyectoVersion] PRIMARY KEY CLUSTERED ([IdProyectoVersion] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

