ALTER TABLE [dbo].[ProyectoVersionDocumento]
    ADD CONSTRAINT [PK_ProyectoVersionDocumentos] PRIMARY KEY CLUSTERED ([IdProyectoVersionDocumento] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

