/*ALTER TABLE [dbo].[PaisFeriados]
    ADD CONSTRAINT [PK_PaisFeriados] PRIMARY KEY CLUSTERED ([IdPaisFeriados] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);*/

