ALTER TABLE [dbo].[PuestoNivel]
    ADD CONSTRAINT [PK_PuestoNivel] PRIMARY KEY CLUSTERED ([IdPuestoNivel] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

