/*ALTER TABLE [dbo].[ProyectoActividadDatos]
    ADD CONSTRAINT [PK_ProyectoActividadDatos] PRIMARY KEY CLUSTERED ([IdProyectoActividadDatos] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);*/

