ALTER TABLE [dbo].[ProyectoPadre]
    ADD CONSTRAINT [PK_ProyectoPadre] PRIMARY KEY CLUSTERED ([IdProyectoPadre] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

