ALTER TABLE [dbo].[PersonaPuestoNivel]
    ADD CONSTRAINT [PK_PersonaPuestoNivel] PRIMARY KEY CLUSTERED ([IdPersona] ASC, [IdPuestoNivel] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);



