ALTER TABLE [dbo].[Proyecto]
    ADD CONSTRAINT [PK_Proyecto] PRIMARY KEY CLUSTERED ([IdProyecto] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

