ALTER TABLE [dbo].[ProyectoVersionActividad]
    ADD CONSTRAINT [PK_ProyectoVersionActividad] PRIMARY KEY CLUSTERED ([IdProyectoVersionActividad] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

