ALTER TABLE [dbo].[ProyectoAsignacion]
    ADD CONSTRAINT [PK_ProyectoAsignacion] PRIMARY KEY CLUSTERED ([IdProyectoAsignacion] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

