ALTER TABLE [dbo].[ProyectoAsignacionActividad]
    ADD CONSTRAINT [PK_ProyectoAsignacionActividad] PRIMARY KEY CLUSTERED ([IdProyectoAsignacionActividad] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

