ALTER TABLE [dbo].[TipoActividad]
    ADD CONSTRAINT [PK_TipoActividad] PRIMARY KEY CLUSTERED ([IdTipoActividad] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

