ALTER TABLE [dbo].[TipoCalculo]
    ADD CONSTRAINT [PK_TipoCalculo] PRIMARY KEY CLUSTERED ([IdTipoCalculo] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

