ALTER TABLE [dbo].[TipoActividadDato]
    ADD CONSTRAINT [PK_TipoActividadDato] PRIMARY KEY CLUSTERED ([IdTipoActividadDato] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

