ALTER TABLE [dbo].[UnidadNegocio]
    ADD CONSTRAINT [PK_UnidadNegocio] PRIMARY KEY CLUSTERED ([IdUnidadNegocio] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

